name: 'My Zigbee Switch'
packageKey: 'my-zigbee-switch'
permissions:
  zigbee: {}
description: "My modified SmartThings driver for Zigbee switch devices"
vendorSupportInformation: "https://support.smartthings.com"
